#!/bin/sh

VENV="venv"

if [ ! -d "$VENV" ]; then
  python -m venv "$VENV"
  source "$VENV"/bin/activate
  pip install -r requirements.txt
else
  source "$VENV"/bin/activate
fi

git config --local user.name "swift.gathering"
git config --local user.email "swift.gathering@gmail.com"
git config --local credential.helper store